# Generated by Django 5.2.4 on 2025-07-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.CharField(max_length=100)),
                ("quantity", models.CharField(max_length=100)),
                ("discount", models.CharField(max_length=100)),
            ],
        ),
    ]
