# Generated by Django 5.2.4 on 2025-08-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("E_commerce_App", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Enter percentage discount",
                        max_digits=5,
                    ),
                ),
            ],
        ),
    ]
