# Generated by Django 5.2.4 on 2025-08-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("E_commerce_App", "0002_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
