# Generated by Django 5.2.4 on 2025-08-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("E_commerce_App", "0003_product_image_alter_product_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("electronics", "Electronics"),
                    ("clothing", "Clothing"),
                    ("books", "Books"),
                    ("grocery", "Grocery"),
                ],
                default="electronics",
                max_length=50,
            ),
        ),
    ]
